/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'add': '&#xe90d;',
            'remove': '&#xe90e;',
            'keyboard_arrow_down': '&#xe90f;',
            'keyboard_arrow_left': '&#xe910;',
            'keyboard_arrow_right': '&#xe911;',
            'keyboard_arrow_up': '&#xe912;',
            'cancel': '&#xe913;',
            'check': '&#xe914;',
            'notifications': '&#xe915;',
            'notifications_none': '&#xe916;',
            'newspaper': '&#xe90b;',
            'news': '&#xe90b;',
            'pencil': '&#xe90c;',
            'write': '&#xe90c;',
            'connection': '&#xe91b;',
            'wifi': '&#xe91b;',
            'mic': '&#xe91e;',
            'microphone': '&#xe91e;',
            'qrcode': '&#xe938;',
            'cart': '&#xe93a;',
            'purchase': '&#xe93a;',
            'coin-dollar': '&#xe93b;',
            'money': '&#xe93b;',
            'phone': '&#xe942;',
            'telephone': '&#xe942;',
            'phone-hang-up': '&#xe943;',
            'telephone2': '&#xe943;',
            'envelop': '&#xe945;',
            'mail': '&#xe945;',
            'location': '&#xe947;',
            'map-marker': '&#xe947;',
            'location2': '&#xe948;',
            'map-marker2': '&#xe948;',
            'map': '&#xe94b;',
            'guide': '&#xe94b;',
            'map2': '&#xe94c;',
            'guide2': '&#xe94c;',
            'printer': '&#xe954;',
            'print': '&#xe954;',
            'mobile': '&#xe958;',
            'cell-phone': '&#xe958;',
            'tablet': '&#xe95a;',
            'mobile3': '&#xe95a;',
            'tv': '&#xe95b;',
            'television': '&#xe95b;',
            'download': '&#xe960;',
            'save': '&#xe960;',
            'upload': '&#xe961;',
            'load': '&#xe961;',
            'redo2': '&#xe968;',
            'right': '&#xe968;',
            'bubble': '&#xe96b;',
            'comment': '&#xe96b;',
            'bubbles3': '&#xe96f;',
            'comments3': '&#xe96f;',
            'user': '&#xe971;',
            'profile2': '&#xe971;',
            'user-tie': '&#xe976;',
            'user5': '&#xe976;',
            'spinner2': '&#xe97b;',
            'loading3': '&#xe97b;',
            'spinner4': '&#xe97d;',
            'loading5': '&#xe97d;',
            'spinner5': '&#xe97e;',
            'loading6': '&#xe97e;',
            'spinner9': '&#xe982;',
            'loading10': '&#xe982;',
            'search': '&#xe986;',
            'magnifier': '&#xe986;',
            'zoom-in': '&#xe987;',
            'magnifier2': '&#xe987;',
            'zoom-out': '&#xe988;',
            'magnifier3': '&#xe988;',
            'enlarge': '&#xe989;',
            'expand': '&#xe989;',
            'shrink': '&#xe98a;',
            'collapse': '&#xe98a;',
            'enlarge2': '&#xe98b;',
            'expand2': '&#xe98b;',
            'shrink2': '&#xe98c;',
            'collapse2': '&#xe98c;',
            'lock': '&#xe98f;',
            'secure': '&#xe98f;',
            'unlocked': '&#xe990;',
            'lock-open': '&#xe990;',
            'cog': '&#xe994;',
            'gear': '&#xe994;',
            'pie-chart': '&#xe99a;',
            'stats': '&#xe99a;',
            'stats-dots': '&#xe99b;',
            'stats2': '&#xe99b;',
            'stats-bars2': '&#xe99d;',
            'stats4': '&#xe99d;',
            'bin': '&#xe9ac;',
            'trashcan': '&#xe9ac;',
            'bin2': '&#xe9ad;',
            'trashcan2': '&#xe9ad;',
            'power-cord': '&#xe9b7;',
            'plugin': '&#xe9b7;',
            'download3': '&#xe9c7;',
            'save5': '&#xe9c7;',
            'upload3': '&#xe9c8;',
            'load3': '&#xe9c8;',
            'sphere': '&#xe9c9;',
            'globe': '&#xe9c9;',
            'earth': '&#xe9ca;',
            'globe2': '&#xe9ca;',
            'link': '&#xe9cb;',
            'chain': '&#xe9cb;',
            'attachment': '&#xe9cd;',
            'paperclip': '&#xe9cd;',
            'eye': '&#xe9ce;',
            'views': '&#xe9ce;',
            'eye-blocked': '&#xe9d1;',
            'views4': '&#xe9d1;',
            'heart': '&#xe9da;',
            'like': '&#xe9da;',
            'warning': '&#xea07;',
            'sign': '&#xea07;',
            'plus': '&#xea0a;',
            'add': '&#xea0a;',
            'minus': '&#xea0b;',
            'subtract': '&#xea0b;',
            'cancel-circle': '&#xea0d;',
            'close': '&#xea0d;',
            'blocked': '&#xea0e;',
            'forbidden': '&#xea0e;',
            'cross': '&#xea0f;',
            'cancel': '&#xea0f;',
            'checkmark': '&#xea10;',
            'tick': '&#xea10;',
            'play2': '&#xea15;',
            'player': '&#xea15;',
            'pause': '&#xea16;',
            'player2': '&#xea16;',
            'stop': '&#xea17;',
            'player3': '&#xea17;',
            'previous': '&#xea18;',
            'player4': '&#xea18;',
            'next': '&#xea19;',
            'player5': '&#xea19;',
            'backward': '&#xea1a;',
            'player6': '&#xea1a;',
            'forward2': '&#xea1b;',
            'player7': '&#xea1b;',
            'play3': '&#xea1c;',
            'player8': '&#xea1c;',
            'pause2': '&#xea1d;',
            'player9': '&#xea1d;',
            'stop2': '&#xea1e;',
            'player10': '&#xea1e;',
            'backward2': '&#xea1f;',
            'player11': '&#xea1f;',
            'forward3': '&#xea20;',
            'player12': '&#xea20;',
            'first': '&#xea21;',
            'player13': '&#xea21;',
            'last': '&#xea22;',
            'player14': '&#xea22;',
            'previous2': '&#xea23;',
            'player15': '&#xea23;',
            'next2': '&#xea24;',
            'player16': '&#xea24;',
            'eject': '&#xea25;',
            'player17': '&#xea25;',
            'volume-high': '&#xea26;',
            'volume': '&#xea26;',
            'volume-medium': '&#xea27;',
            'volume2': '&#xea27;',
            'volume-mute2': '&#xea2a;',
            'volume5': '&#xea2a;',
            'loop2': '&#xea2e;',
            'repeat2': '&#xea2e;',
            'arrow-up': '&#xea32;',
            'up': '&#xea32;',
            'arrow-right': '&#xea34;',
            'right3': '&#xea34;',
            'arrow-down': '&#xea36;',
            'down': '&#xea36;',
            'arrow-left': '&#xea38;',
            'left3': '&#xea38;',
            'arrow-up2': '&#xea3a;',
            'up2': '&#xea3a;',
            'arrow-right2': '&#xea3c;',
            'right4': '&#xea3c;',
            'arrow-down2': '&#xea3e;',
            'down2': '&#xea3e;',
            'arrow-left2': '&#xea40;',
            'left4': '&#xea40;',
            'circle-up': '&#xea41;',
            'up3': '&#xea41;',
            'circle-right': '&#xea42;',
            'right5': '&#xea42;',
            'circle-down': '&#xea43;',
            'down3': '&#xea43;',
            'circle-left': '&#xea44;',
            'left5': '&#xea44;',
            'shift': '&#xea4f;',
            'checkbox-checked': '&#xea52;',
            'checkbox': '&#xea52;',
            'checkbox-unchecked': '&#xea53;',
            'checkbox2': '&#xea53;',
            'radio-checked2': '&#xea55;',
            'radio-button2': '&#xea55;',
            'radio-unchecked': '&#xea56;',
            'radio-button3': '&#xea56;',
            'crop': '&#xea57;',
            'resize': '&#xea57;',
            'share': '&#xea7d;',
            'out': '&#xea7d;',
            'mail3': '&#xea84;',
            'contact3': '&#xea84;',
            'mail4': '&#xea85;',
            'contact4': '&#xea85;',
            'facebook2': '&#xea91;',
            'brand11': '&#xea91;',
            'whatsapp': '&#xea93;',
            'brand13': '&#xea93;',
            'youtube': '&#xea9d;',
            'brand21': '&#xea9d;',
            'apple': '&#xeabe;',
            'brand53': '&#xeabe;',
            'android': '&#xeac0;',
            'brand55': '&#xeac0;',
            'windows8': '&#xeac2;',
            'brand57': '&#xeac2;',
            'skype': '&#xeac5;',
            'brand60': '&#xeac5;',
            'reddit': '&#xeac6;',
            'brand61': '&#xeac6;',
            'linkedin': '&#xeac9;',
            'brand64': '&#xeac9;',
            'pinterest': '&#xead1;',
            'brand72': '&#xead1;',
            'file-pdf': '&#xeadf;',
            'file10': '&#xeadf;',
            'file-openoffice': '&#xeae0;',
            'file11': '&#xeae0;',
            'file-word': '&#xeae1;',
            'file12': '&#xeae1;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/icon/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
